name: ci
on:
  workflow_dispatch:
  pull_request:

jobs:
  prettier-test:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{js,ts,jsx,tsx,css,md}
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.17.5'
      - name: Test - install dependencies
        run: npm install
      - name: Test - build
        run: npm run build
        env:
          CI: ''
      - name: Test - run test
        run: npm test
