name: deploy
on:
  push:
    branches:
      - main

jobs:
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '18.12.0'
      - name: Test - install dependencies
        run: npm install
      - name: Test - build
        run: npm run build
        env:
          CI: ''
      - name: Test - run test
        run: npm test

  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    needs: [jest-test]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '18.12.0'
      - name: Install dependencies
        run: npm install
      - name: Build React app
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
