name: deploy
on:
  push:
    branches:
      - main

jobs:
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '18.12.0'
      - name: Test - install dependencies
        run: npm install
      - name: Test - build
        run: npm run build
        env:
          CI: ''
      - name: Test - run test
        run: npm test

  deploy-to-heroku:
    runs-on: ubuntu-latest
    needs: [jest-test]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Publish Release
        id: release
        uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: minor
          tag_prefix: v
      - name: Deploy to production
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: portfolio-luke-malinowski
          heroku_email: 'malinowski.luke@icloud.com'
          branch: ${GITHUB_REF_NAME}
        env: # Env vars prefixed with HD_ will have the "HD_" stripped automatically by heroku-deploy
          HD_DD_VERSION: ${{steps.release.outputs.tag_name}}
